name: Generate Dependency Graphs
on:
  workflow_dispatch:
    push:
      branches: [ main ]

jobs:
  dependency_graphs:
    name: Dependency Graphs
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout main
      uses: actions/checkout@v3
    - name: Generate Package Dependency Graphs
      uses: ./.github/actions/package-dependency-graph
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update package dependency graphs
