name: Generate Dependency Graphs
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

env:
  DOT_OUTPUT: 'images/dependencies.dot'
  GRAPH_OUTPUT: 'images/dependencies.svg'

jobs:
  dependency_graphs:
    name: Dependency Graphs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout main
      uses: actions/checkout@v3
    - name: Install Graphviz
      run: |
        sudo apt-get update
        sudo apt-get install graphviz
    - name: Generate Package Dependency Graphs
      run: |
        NO_DEPENDENCY_MESSAGE="No external dependencies found"

        for dir in Packages/*/ ; do
          dot_file="$dir$DOT_OUTPUT"
          swift package --package-path $dir show-dependencies --format dot -o $dot_file
          if ! grep -q $NO_DEPENDENCY_MESSAGE $dot_file; then
            dot -Tsvg $dot_file > "$dir$GRAPH_OUTPUT"
          fi
        done
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update package dependency graphs
